# Copy to /etc/init/docker-piond.conf
description "Docker container for piond p2p node"
start on filesystem and started docker
stop on runlevel [!2345]
respawn
pre-start script
  # Clean-up if left behind
  docker rm -f piond-node || true
  
  # Attempt to always update and fail silently if the network isn't ready
  docker pull pioncoin/piond || true
end script
script
  exec docker run --rm -v piond-data:/pion --name=piond-node --rm -p 9954:9954 -p 127.0.0.1:9953:9953 pioncoin/piond
end script
